config/routes.rb
Rails.application.routes.draw do
  post 'shifts/import', to: 'shifts#import'

  devise_for :users, path: 'volunteers', path_names: { sign_in: 'login', sign_out: 'logout', registration: 'register' }, controllers: { registrations: "users/registrations" }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
    

  root to: 'users#index'
  
  get '/volunteers/profiles/:id', to: 'users#show', as: :user
  get '/volunteers', to: 'users#index', as: :users

end

app/models/user.rb
class User < ApplicationRecord
  require 'csv'
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
        # :confirmable
        
  enum gender: [:male, :female, :other, :prefer_not_to_disclose]
  enum contact_method: [:phone, :email]
         
  attr_accessor :other_interests
  validates :email, uniqueness: true, allow_nil: true
  validates :name, uniqueness: true
  validates :name, presence: true
  validates :other_gender, presence: true, if: Proc.new {|u| u.other?}
  validates :city, format: { with: /\A[a-zA-Z]+\z/ }, allow_blank: true
  validates :state, format: { with: /\A[a-zA-Z]{2}\z/ }, allow_blank: true
  
  validate :different_home_work_phone, :home_or_work_phone
  
  def different_home_work_phone
    errors.add(:home_phone) if home_phone == work_phone
  end
  
  def home_or_work_phone
    errors.add(:home_phone) if home_phone.blank? and work_phone.blank?
  end
  
  has_attached_file :avatar, styles: { medium: "180x180>", thumb: "50x50>" }, default_url: "/assets/blank-avatar.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  
  has_and_belongs_to_many :interests
  belongs_to :organization, optional: true
  
  has_many :donations
  has_many :shifts
  
  def self_import(file)
    CSV.foreach(file.path, headers: true) do |row|
      User.create! row.to_hash
    end
  end
  
  def email_required?
    false
  end

  def email_changed?
    false
  end
  
  def will_save_change_to_email?
    false
  end
end

app/controllers/user_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    
    def user_params
        params.require(:firstname, :lastname, :password, :email, :phone, :dob).permit(:interests)
    end
  
    # GET /users/new
    def new
        render layout: "users"
    end
    
    def edit
        @user = current_user
    end
    
    # POST /users
    # POST /users.json
    def create
        @user = User.create!(user_params)
        respond_to do |format|
          if @user.save
            format.html { redirect_to @user, notice: 'Interest was successfully created.' }
            format.json { render :show, status: :created, location: @user }
          else
            format.html { render :new }
            format.json { render json: @user.errors, status: :unprocessable_entity }
          end
        end
        redirect_to user_path(@user)
    end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  
  # GET /resource/sign_up
  def new
    @dogs = Interest.dog_interests
    @cats = Interest.cat_interests
    @other = Interest.other_interests
    super
  end

  # POST /resource
  def create
    @dogs = Interest.dog_interests
    @cats = Interest.cat_interests
    @other = Interest.other_interests
    super
    if params[:interests] then
      params[:interests].each do |int| 
        @interest = Interest.find_by name: int
        @user.interests << @interest
      end
    end
    if params[:dogs] then
      params[:dog_interests].each do |int|
        @interest = Interest.find_by name: "Dog " + int.downcase
        @user.interests << @interest
      end
    end
    if params[:cats] then
      params[:cat_interests].each do |int|
        @interest = Interest.find_by name: "Cat " + int.downcase
        @user.interests << @interest
      end
    end
    if params[:other] then
      @int_params = params[:other_interests].split(',')
      @int_params.each do |int|
        int = int.strip.downcase.capitalize
        if !(Interest.find_by name: int)
          Interest.create!(name: int)
        end
        @interest = Interest.find_by name: int
        @user.interests << @interest
      end
    end
  end

  # GET /resource/edit
  def edit
    @dogs = Interest.dog_interests
    @cats = Interest.cat_interests
    @other = Interest.other_interests
    @all = Interest.all_interests
    @user = current_user
    @dogDisabled = @user.interests.where("name like ?", "%Dog%").present? ? false : true
    @catDisabled = @user.interests.where("name like ?", "%Cat%").present? ? false : true
    super
  end

  # PUT /resource
  def update
    @dogs = Interest.dog_interests
    @cats = Interest.cat_interests
    @other = Interest.other_interests
    @all = Interest.all_interests
    if (params[:user][:email] == "" || params[:user][:name] == "")
      if (params[:user][:name] == "")
        resource.errors.add(:name, "field may not be blank.")
      end
      if (params[:user][:email] == "")
        resource.errors.add(:email, "field may not be blank.")
      end
      respond_with resource
    else
      @user.interests.clear
      if params[:interests] then
        params[:interests].each do |int| 
          @interest = Interest.find_by name: int
          @user.interests << @interest
        end
      end
      if params[:dogs] then
        params[:dog_interests].each do |int|
          @interest = Interest.find_by name: "Dog " + int.downcase
          @user.interests << @interest
        end
      end
      if params[:cats] then
        params[:cat_interests].each do |int|
          @interest = Interest.find_by name: "Cat " + int.downcase
          @user.interests << @interest
        end
      end
      if params[:other] then
        @int_params = params[:other_interests].split(',')
        @int_params.each do |int|
          int = int.strip.downcase.capitalize
          if !(Interest.find_by name: int)
            Interest.create!(name: int)
          end
          @interest = Interest.find_by name: int
          @user.interests << @interest
        end
      end
      super
    end
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    user_path(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    user_path(resource)
  end
  
  # The default url to be used after updating a resource. You need to overwrite
  # this method in your own RegistrationsController.
  def after_update_path_for(resource)
    user_path(resource)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    include ApplicationHelper
    before_action :auth_user!
    
    def user_params
        params.require(:name, :password, :email, :home_phone, :dob).permit(:avatar)
    end
    
    def index
		if params.key?(:sort_users)
			session[:sort_users] = params[:sort_users]
		elsif session.key?(:sort_users)
			redirect_to sort_users: session[:sort_users] and return
		end
		
        @users = User.all.order(session[:sort_users])
    end
  
    def show
        id = params[:id] # retrieve post ID from URI route
        @user = User.find(id) # look up movie by unique ID
        respond_to do |format|
            
            format.html
            format.json
            format.pdf {render template: 'users/report', pdf: 'Report' } # Excluding ".pdf" extension.

        end
    end
  
    # GET /users/new
    def new
     #   render layout: "site"
    end
    
    def edit
        @user = current_user
    end
    
    def create
        @user = User.create!(user_params)
        respond_to do |format|
          if @user.save
            format.html { redirect_to @user, notice: 'Interest was successfully created.' }
            format.json { render :show, status: :created, location: @user }
          else
            format.html { render :new }
            format.json { render json: @user.errors, status: :unprocessable_entity }
          end
        end
        redirect_to user_path(@user)
    end
  
    def import 
        User.import(params[:file])
        redirect_to root_url, notice: "Activity Data imported!"
    end
end

app/views/users/index.html.haml
%body
  %h1.centered.padded Volunteers
  %table#posts{style:"margin-bottom:1em; table-layout: fixed; width: 100%"}
    %thead
      %tr
        %th{:class => "#{('hilite' if session[:sort_users] == 'name')}"}
          = link_to "Name", users_path(:sort_users => 'name'), id: "name_header"
        %th{:class => "#{('hilite' if session[:sort_users] == 'created_at')}"}
          = link_to "Date Joined", users_path(:sort_users => 'created_at'), id: "joined_header"
    %tbody
      / Reverse_Each so that most recent user appears at the top
      - @users.each do |user|
        %tr
          %td
            = link_to user.name, user_path(user), class:"link"
          %td
            = user.created_at.in_time_zone('Central Time (US & Canada)').strftime("%b %e, %Y")
            
    %br/
    %br/
      
    = form_tag shifts_import_path, multipart: true do
      = file_field_tag "file"
      = submit_tag "Import CSV"

app/views/users/report.pdf.haml
!!!
%html
  %body
    :css
      h1{
          border-bottom: 7px solid #41009A;
          
      }
      body{
          background-image:#{wicked_pdf_image_tag 'CatDogBanner.PNG'} ;
      }
      profile{
          position: absolute;
          TOP:700px; 
          LEFT:400px;
          border: 7px solid #41009A ;
          border-radius: 25px;
          width: 280px;
          height: 280px; 
          background-color:#B3B3B3
      }
      
      name {
          font-size: 30px;
          color:#41009A ;
          position: absolute; 
          TOP:620px; 
          LEFT:400px;
          width: 280px;
          height: 30px;
      }
      
      shifts {
          position: absolute; 
          TOP:500px; 
          RIGHT:400px;
          width: 280px;
          height: 480px;
          border: 7px solid #41009A ;
          border-radius: 25px;
      }
      monthly-hours {
          position: absolute; 
          TOP:115px; 
          RIGHT:400px;
          width: 280px;
          height: 180px;
          background-color:#B3B3B3
          
      }
      
      weekly-hours {
          position: absolute; 
          TOP:310px; 
          RIGHT:400px;
          width: 280px;
          height: 180px;
          background-color:#B3B3B3
          
      }
      
      graph-description{
          position: absolute; 
          TOP:115px; 
          LEFT:400px;
          width: 280px;
          height: 180px;
          border: 7px solid #41009A ;
          border-radius: 25px;
          
      }
    %title
      Volunteer Report for #{@user.name}
    %div{:align => "left"}
      = @user.name
    %h1
      %font{:color => "#B3B3B3", :size => "30"}
        Volunteer Report
      = wicked_pdf_image_tag 'palslogopdf.jpg', :style => "position:absolute; TOP:0px; RIGHT:0px; HEIGHT:100; WIDTH:230;"
      = wicked_pdf_image_tag 'blank-avatar.png', :style => "position:absolute; TOP:320px; LEFT:400px; HEIGHT:280px; WIDTH:280px; border-radius: 50%;"
    %name{:align => "center"}
      = @user.name
    %profile{:align => "center"}
      %br/
      %br/
      Date of birth: #{@user.dob}
      %br/
      Email: #{@user.email}
      %br/
      Organization: 
      %br/
      Phone: #{@user.home_phone}
      %br/
      Shifts Worked: 
      %br/
      Hours Worked: 
      %br/
    %weekly-hours{:align => "center"}
      Graph of Hours worked daily
    %monthly-hours{:align => "center"}
      Graph of Hours worked weekly
    %graph-description
      Stats on Weekly Graph:
      %br/
      Stats on Daily Graph:
    %shifts
      Shifts column;

app/views/users/show.html.haml
%body
  .row
    .col-md-12
      %h2{:style => "text-align:center"} #{@user.name}'s Profile
  .row
    .col-md-2
    .col-md-3
      .centered
        %br/
        - if @user.avatar_file_name
          %img{src: "/system/users/avatars/000/000/" + params[:id].rjust(3, "0") + "/medium/" + @user.avatar_file_name, alt: "Image not found"} 
        - else
          %img{src: "/assets/blank-avatar.png", alt: "Image not found"}
        %br/
        %br/
        %b About #{@user.name}:
        %br/
        = @user.bio
    .col-md-5
      %div{:style => "margin-left:20px"}
        %h5 Personal Information
        %div{style: "font-size:17px"}
          %b Birthdate:
          = @user.dob.strftime("%B %e, %Y")
          %br/
          %b Interests:
          = @user.interests.map(&:name).join(", ")
        %hr.line/
        %h5 Contact Information
        %div{style: "font-size:17px"}
          %b Phone:
          = @user.home_phone
          %br/
          %b Email:
          = @user.email
    .col-md-2
  .row
    .col-md-12
      %br/
      -if current_user != @user
        %br/
      -else
        %div{:style => "text-align:center"}
          = button_to 'Edit profile', edit_user_registration_path, method: :get, class: "purple default", style: "font-size:1.3em;padding:10px 20px"
        %br/