config/routes.rb
Rails.application.routes.draw do
  post 'shifts/import', to: 'shifts#import'

  devise_for :users, path: 'volunteers', path_names: { sign_in: 'login', sign_out: 'logout', registration: 'register' }, controllers: { registrations: "users/registrations" }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
    

  root to: 'users#index'
  
  get '/volunteers/profiles/:id', to: 'users#show', as: :user
  get '/volunteers', to: 'users#index', as: :users

end

app/views/admin/volunteers/_graphs.html.haml
-# include the chartkick library
= javascript_include_tag "//www.google.com/jsapi"
= javascript_include_tag "application", "chartkick"

%h3 Graphs
-# for getting desired sort by period
= label_tag :sort_by, "Sort by"
= select_tag :sort_by, options_for_select(["year", "quarter", "month", "week", "day", ["hour", "hour_of_day"]],
                                          selected: selected, disabled: disabled),
                       { class: 'default-select' }

= line_chart day_counts, id: "shifts-chart", label: "Shifts", curve: false, title: "Shifts by Day",
                         library: {vAxis: {ticks: day_counts.values}}
                         
:javascript
  $().ready(function() {
    function options_default(sb) {
      return { label: "Shifts", curve: false, title: "Shifts by " + sb };
    }
    -# updates the charts with the user's select choice
    $("#sort_by").change(function() {
      $.ajax("#{shifts_admin_volunteer_path(params[:id])}", {
               data: { sort_by: $("#sort_by").val() },
               success: function(data) {
                 Chartkick.charts["shifts-chart"].updateData(data, options_default($("#sort_by :selected").text()))
               },
               error: function(xhr, status, err) {
                 alert("Something went wrong!")
                 console.debug(err)
               }
      })
    })
  })