config/routes.rb
Rails.application.routes.draw do
  post 'shifts/import', to: 'shifts#import'

  devise_for :users, path: 'volunteers', path_names: { sign_in: 'login', sign_out: 'logout', registration: 'register' }, controllers: { registrations: "users/registrations" }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
    

  root to: 'users#index'
  
  get '/volunteers/profiles/:id', to: 'users#show', as: :user
  get '/volunteers', to: 'users#index', as: :users

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{name: "viewport", content: "width=device-width, initial-scale=1, shrink-to-fit=no", "http-equiv" => "Content-Type"}/
    %title PALS Volunteer Portal
    = stylesheet_link_tag 'application', 'media' => 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    %div.container.title
      %div.row.title
        %div.col-md-6
          %nav.navbar.navbar-expand-md.navbar-light
            %img{src: '/assets/palslogotp.png', alt: 'PALS', width: '115', height: '56'}
            %span.h1.title Volunteer Portal
        %div.col-md-6
          %nav.navbar.navbar-expand-md.navbar-light.navbar-toggleable-sm
            %button.navbar-toggler.navbar-toggler-right{type:"button", "data-toggle" => "collapse", "data-target" => "#navbarSupportedContent", "aria-controls" => "#navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation"}
              %span.navbar-toggler-icon
            #navbarSupportedContent.collapse.navbar-collapse
              %ul.navbar-nav.ml-md-auto
                - if user_signed_in?
                  %li.nav-item{style:"display:inline-block"}
                    = button_to 'Volunteers', users_path, {method: :get, class: "purple default"}
                  %li.nav-item{style:"display:inline-block"}
                    = button_to 'My Profile', user_path(current_user), {method: :get, class: "purple default"}
                  %li.nav-item{style:"display:inline-block"}
                    = button_to 'Log Out', destroy_user_session_path, {method: :delete, class:"purple default"}
                - elsif admin_user_signed_in?
                  %li.nav-item{style:"display:inline-block"}
                    = button_to 'Dashboard', admin_root_path, {method: :get, class: "purple default"}
                  %li.nav-item{style:"display:inline-block"}
                    = button_to 'Log Out', destroy_admin_user_session_path, {method: :delete, class:"purple default"}
                - else
                  %li.nav-item{style:"display:inline-block"}
                    =button_to 'Sign up', new_user_registration_path, {method: :get, class: "purple default"}
                  %li.nav-item{style:"display:inline-block"}
                    =button_to 'Log in', user_session_path, {method: :get, class: "purple default"}
                  
    #main.full
      %head
        / Include Bootstrap and HTML Kickstart (for style)
        %link{:crossorigin => "anonymous", :href => "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css", :integrity => "sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb", :rel => "stylesheet"}/
        %link{:href => "/assets/kickstart.css", :media => "all", :rel => "stylesheet"}/
        = stylesheet_link_tag 'application'
      %body.background
        .container.full.grad-border-white{:style => "background-color:white; height:100%"}
          .header_padding
            - if flash[:notice]
              %div.alert.alert-success{:role => "alert"}
                #notice.success= flash[:notice]
            - elsif flash[:warning]
              %div.alert.alert-danger{:role => "alert"}
                #warning.message= flash[:warning]

          = yield